#!/bin/bash

BFH_USER=$1
DB='/home/supergalley/docker/BannedFromHeaven/data/jokes.db'
HASH='scrypt:32768:8:1$PaNhxMltD0WsgcPp$f821b25947bfdc8171d3c313c8aa9750996a58be82652651d008047705b9a36b03a33521add595e90a40487058f454562cca0055e5bf89fe331f9bb6ce1ca0a8'

if [ -z "$1" ]; then
    echo "Usage: $0 username"
    exit 1
fi

sqlite3 "$DB" <<EOF
UPDATE users
SET password_hash='$HASH'
WHERE username='$BFH_USER';
SELECT id, username
FROM users
WHERE username='$BFH_USER';
EOF

echo "Password for $BFH_USER set to ChangeMe123"

