#!/usr/bin/env python3
"""One-shot seeder: rich, on-brand subcategories for BFH categories."""
from __future__ import annotations

import re
import sys

from app import create_app, db
from app.models import Category, Subcategory


def slugify(name: str, max_len: int = 60) -> str:
    s = (name or "").strip().lower()
    s = re.sub(r"[^a-z0-9]+", "", s)
    if not s:
        s = re.sub(r"[^a-z0-9]+", "-", (name or "").strip().lower()).strip("-")
        s = re.sub(r"-+", "-", s)
    return (s or "item")[:max_len]


# Map by category slug -> subcategory display names
SUBS: dict[str, list[str]] = {
    "aids": [
        "Dying from AIDS",
        "Africa AIDS Epidemic",
        "Cure for AIDS",
        "AIDS Denial",
        "HIV Positive",
        "Blood Transfusion",
        "Gay Plague Era",
        "AIDS Awareness Ribbon",
        "AZT and Early Drugs",
        "Needle Sharing",
        "Magic Johnson",
        "Freddie Mercury",
        "Bareback Roulette",
        "Undetectable Viral Load",
        "AIDS Orphans",
    ],
    "accidents": [
        "Workplace Accident",
        "Car Crash",
        "Slip and Fall",
        "Industrial Mishap",
        "Lawnmower Incident",
        "DIY Disaster",
        "Bike vs Car",
        "Scaffolding Collapse",
        "Hot Oil / Kitchen Burn",
        "Amputation Story",
        "Insurance Claim",
        "Darwin Award Material",
        "Chainsaw",
        "Ladder Fall",
        "Electrocution",
    ],
    "adult": [
        "One Night Stand",
        "Swingers",
        "Strip Club",
        "OnlyFans Energy",
        "Dirty Talk",
        "Kink / Fetish",
        "Threesome",
        "Sex Toy Fail",
        "Hotel Hookup",
        "Friends with Benefits",
        "Tinder / Dating App",
        "Public Indecency",
        "MILF / DILF",
        "Anal",
        "Oral",
        "BDSM Light",
        "Cheating",
    ],
    "age": [
        "Nursing Home",
        "Dementia / Alzheimer's",
        "Hip Replacement",
        "Bingo Night",
        "Old Man Driving",
        "Pension / Benefits",
        "Depends Undergarments",
        "Funeral Already Booked",
        "Young vs Old",
        "Grandparenting Badly",
        "Age Gap Dating",
        "Retirement",
        "Hearing Aid",
        "Dentures",
        "Senior Sex",
    ],
    "alcohol": [
        "Drunk Driver",
        "Hangover",
        "Alcoholic Parent",
        "Pub Lock-In",
        "Cocaine",
        "Heroin / Opioids",
        "Weed / Stoners",
        "Ketamine",
        "MDMA / Club Drugs",
        "Crack",
        "Rehab Fail",
        "AA Meeting",
        "Booze Cruise",
        "Underage Drinking",
        "Blackout Stories",
        "Meth",
        "Fentanyl",
        "Prescription Abuse",
    ],
    "animals": [
        "Dogs",
        "Cats",
        "Farm Animals",
        "Roadkill",
        "Vet Bills",
        "Bestiality Jokes",
        "Zoo Escape",
        "Animal Cruelty Punchline",
        "Pigeon / Pest",
        "Endangered Species",
        "Pet Euthanasia",
        "Horses",
        "Insects",
        "Sharks",
        "Monkey Business",
    ],
    "aviation": [
        "Plane Crash",
        "Turbulence",
        "Pilot Error",
        "Airport Security",
        "Ryanair / Budget Airline",
        "Black Box",
        "Mid-Air Collision",
        "Cabin Crew",
        "Lost Luggage",
        "9/11 Adjacent",
        "Helicopter",
        "Parachute Fail",
        "Air Rage",
        "Flight Attendant",
        "Engine Failure",
    ],
    "bbc": [
        "License Fee",
        "Newsreaders",
        "Jimmy Savile",
        "Blue Peter",
        "Strictly",
        "Doctor Who",
        "BBC Bias",
        "Panel Shows",
        "Radio 4",
        "Children's TV",
        "BBC Scandals",
        "Presenters",
        "EastEnders",
        "Weather Girl",
        "Auntie Beeb",
    ],
    "babies": [
        "Crying Baby",
        "Nappy Disaster",
        "Postpartum",
        "IVF / Fertility",
        "Abortion Punchline",
        "Stillbirth Dark",
        "Shaken Baby Joke",
        "Colic",
        "Breastfeeding in Public",
        "Baby Daddy",
        "Twins / Multiples",
        "Sudden Infant Death",
        "Baby Names",
        "Sleep Deprivation",
        "Toddler Terror",
    ],
    "blind": [
        "Guide Dog",
        "Braille",
        "Stepped in Dog Shit",
        "White Cane",
        "Blind Date Literal",
        "Eye Transplant",
        "Blind Beggar",
        "Audio Description",
        "Mistaken Identity",
        "Parking for Blind",
        "Stevie Wonder",
        "Glass Eye",
        "Partially Sighted",
        "Dark Humor Literally",
    ],
    "boats": [
        "Sinking Ship",
        "Man Overboard",
        "Pirate",
        "Cruise Ship",
        "Seasickness",
        "Ferry Disaster",
        "Navy",
        "Yacht Wanker",
        "Titanic",
        "Fishing Boat",
        "Coastguard",
        "Shark Infested",
        "Life Jacket",
        "Captain Goes Down",
    ],
    "cancer": [
        "Chemo",
        "Bald from Cancer",
        "Terminal Diagnosis",
        "Breast Cancer",
        "Lung Cancer / Smoking",
        "Childhood Cancer",
        "Remission Then Relapse",
        "Cancer Survivor Brag",
        "Tumour Jokes",
        "Oncology Ward",
        "Macmillan Nurse",
        "Prostate",
        "Brain Tumour",
        "Hospice",
        "Cure Claims",
    ],
    "celebrities": [
        "Hollywood A-Listers",
        "Reality TV Stars",
        "Pop Stars",
        "Sports Celebs",
        "Influencers",
        "Cancelled Celebrities",
        "Plastic Surgery Celebs",
        "Needy Famous People",
        "Royal Adjacent",
        "Has-Beens",
        "Child Stars Grown Wrong",
        "Sex Tape Celebs",
        "Award Shows",
        "Paparazzi",
    ],
    "celebritydeath": [
        "Overdose",
        "Plane Crash Celebs",
        "Suicide of Famous",
        "Murdered Stars",
        "Old Age Celebs",
        "COVID Era Deaths",
        "Stage Collapse",
        "Car Crash Celebs",
        "Murder-Suicide",
        "Conspiracy Deaths",
        "Faked Death Theories",
        "Funeral Spectacle",
        "Legacy Ruined",
        "Died Too Young",
        "Died Too Late",
    ],
    "christmas": [
        "Santa is Dead",
        "Christmas Divorce",
        "Office Party",
        "Turkey Disaster",
        "Kids Spoilt Rotten",
        "Religious Christmas",
        "Boxing Day Hangover",
        "Secret Santa Fail",
        "Christmas TV",
        "Family Arguments",
        "Presents Nobody Wanted",
        "Elf on the Shelf Creep",
        "Nativity",
        "New Year Overlap",
        "Christmas Cancelled",
    ],
    "cosplay": [
        "Convention Creep",
        "Rule 34 Cosplay",
        "Furries Adjacent",
        "Armour Fail",
        "Body Paint Disaster",
        "Weeb Energy",
        "Comic-Con",
        "Sexualised Characters",
        "DIY Costume Fail",
        "Anime Girls",
        "Superhero Spandex",
        "Prop Weapons",
        "Cosplay Gatekeeping",
    ],
    "crime": [
        "Robbery",
        "Burglary",
        "Fraud / Scam",
        "Assault",
        "Arson",
        "Drug Dealing",
        "Organised Crime",
        "Serial Killer Fanboy",
        "Police Corruption",
        "Witness Protection",
        "Courtroom",
        "DNA Evidence",
        "Crime of Passion",
        "White Collar",
        "Knife Crime",
        "Gun Crime",
        "Cybercrime",
    ],
    "cyclists": [
        "Lycra Brigade",
        "Red Light Jumpers",
        "Cycle Lane Wars",
        "Knocked Off Bike",
        "Tour de France Doping",
        "E-Bike Menace",
        "Pavement Cyclists",
        "Helmet Hair",
        "Bike Thieves",
        "Critical Mass",
        "Motorist vs Cyclist",
        "Deliveroo Riders",
        "Fixed Gear Hipsters",
    ],
    "dad": [
        "Pun Overload",
        "BBQ Dad",
        "Tool Shed Wisdom",
        "Dad Bod",
        "Awkward Dad Dance",
        "Dad Joke Meta",
        "Lawn Care",
        "Socks and Sandals",
        "Forgotten Birthday",
        "Silent Dinner Table",
        "Dad at Sports Day",
        "DIY Dad Fail",
        "Dad Jeans",
    ],
    "dark": [
        "Existential Nihilism",
        "Genocide Punchline",
        "School Shooting Dark",
        "Holocaust Adjacent",
        "Famine",
        "War Crimes",
        "Torture Chamber",
        "Serial Killer",
        "Body in the Freezer",
        "Cannibalism",
        "Cult Mass Suicide",
        "Nuclear Winter",
        "Plague",
        "Child Endangerment Dark",
        "Necrophilia Adjacent",
        "Snuff Energy",
        "Human Trafficking Dark",
    ],
    "death": [
        "Funeral",
        "Cremation",
        "Open Casket",
        "Will Reading",
        "Widow / Widower",
        "Dead Body Discovery",
        "Obituary",
        "Graveyard",
        "Autopsy",
        "Ashes Scattered Wrong",
        "Near Death",
        "Reaper Jokes",
        "Burial at Sea",
        "Haunted by the Dead",
        "Sudden Death",
    ],
    "disablity": [
        "Wheelchair",
        "Amputee",
        "Deaf / Hard of Hearing",
        "Paralysis",
        "Accessible Parking Abuse",
        "Disabled Toilet",
        "Inspiration Porn Mockery",
        "Service Animal",
        "Speech Impediment",
        "Learning Disability",
        "Adaptive Sports",
        "Benefits / PIP",
        "Crip Jokes Meta",
        "Guide Dog Adjacent",
    ],
    "disease": [
        "COVID / Pandemic",
        "STD / STI",
        "Plague / Black Death",
        "Ebola",
        "Flu Season",
        "Contagious Cough",
        "Quarantine",
        "Vaccine Wars",
        "Antivax",
        "Hospital Superbug",
        "Leprosy",
        "Measles",
        "Scurvy / Old Disease",
        "Parasites",
        "Mental as Physical",
    ],
    "medical": [
        "GP Waiting Room",
        "A&E Nightmare",
        "Nurse Shortage",
        "Surgeon Error",
        "Wrong Limb Amputated",
        "Medical Bill / Private",
        "NHS Queue",
        "Bedside Manner",
        "Organ Transplant",
        "Blood Donation",
        "Anaesthetic Fail",
        "Malpractice",
        "Medical Student",
        "Hospital Food",
        "Shift Work Hell",
        "Prescription Mix-up",
    ],
    "wifebeater": [
        "Black Eye Excuses",
        "Police Called Again",
        "Restraining Order",
        "Court Case Dropped",
        "Cycle of Abuse",
        "Drunk Rage",
        "Neighbour Complaints",
        "Shelter Referral",
        "I Walked Into a Door",
        "Kids Watching",
        "Apology Flowers",
        "Repeat Offender",
        "Mutual Combat Claim",
    ],
    "trump": [
        "MAGA",
        "Trump Hair",
        "Impeachment",
        "January 6",
        "Trump Golf",
        "Fake News",
        "Wall / Border",
        "Trump Kids",
        "Epstein Adjacent Trump",
        "Stormy Daniels",
        "Covfefe",
        "Trump Trial",
        "Orange Man",
        "Trump Rally",
        "Trump vs Media",
        "Make America Jokes Again",
    ],
    "downs": [
        "Special Olympics",
        "Classroom Integration",
        "Mongoloid Slur Era",
        "Parenting Downs",
        "Workplace Inclusion",
        "Facial Features Jokes",
        "Speech Delay",
        "Love and Dating",
        "Care Home",
        "Genetic Screening",
        "Sibling of Downs",
        "TV Representation",
    ],
    "dumb": [
        "Flat Earth",
        "Failed School",
        "Can't Read",
        "IQ of a Plant",
        "TikTok Education",
        "Conspiracy Brain",
        "Gullible",
        "Wrong End of Stick",
        "Village Idiot",
        "Goldfish Memory",
        "Spell Check Off",
        "Common Sense Vacuum",
        "Thick as Two Planks",
    ],
    "epstein": [
        "Island",
        "Client List",
        "Clinton Adjacent",
        "Trump Adjacent Epstein",
        "Suicide Watch Fail",
        "Maxwell",
        "Flight Logs",
        "Massage Room",
        "Underage Victims",
        "Elite Cover-up",
        "Jail Cell Camera",
        "Blackmail Theory",
        "Died of Suicide",
        "Not a Coincidence",
    ],
    "fat": [
        "Mobility Scooter",
        "All You Can Eat",
        "Plane Seatbelt Extender",
        "Fat Acceptance",
        "Gastric Band",
        "Heart Attack Risk",
        "Sweat and Folds",
        "Diet Fail",
        "Fast Food",
        "Plus Size Fashion",
        "Can't See My Dick",
        "Chair Collapse",
        "Body Positivity Mock",
        "Super Size Me",
        "Diabetes Type 2",
    ],
    "football": [
        "Premier League",
        "Hooligans",
        "VAR Controversy",
        "Own Goal",
        "Transfer Window",
        "Manager Sacking",
        "World Cup",
        "Penalty Shootout",
        "Stadium Disaster",
        "Fan Violence",
        "Match Fixing",
        "WAG Culture",
        "Local Derby",
        "Relegation",
        "Footballer Affairs",
    ],
    "gambling": [
        "Casino",
        "Slot Machines",
        "Betting Shop",
        "Lost the House",
        "Online Gambling",
        "Poker Face Fail",
        "Fixed Race",
        "Loan Shark",
        "Problem Gambler",
        "Bingo",
        "Lottery",
        "Crypto Gambling",
        "Bookie Violence",
        "Wife Doesn't Know",
    ],
    "general": [
        "Observational",
        "Everyday Life",
        "Shower Thoughts",
        "Tech Annoyances",
        "Queueing Britishly",
        "Weather Small Talk",
        "Customer Service",
        "Public Transport",
        "Neighbours",
        "Shopping",
        "Internet Culture",
        "Random Nonsense",
        "Life Advice Bad",
    ],
    "greenshit": [
        "Net Zero",
        "Climate Protest Glue",
        "Ulez / Congestion",
        "Electric Cars",
        "Wind Turbines",
        "Recycling Lies",
        "Meat Tax",
        "Flight Shame",
        "Greta Energy",
        "Carbon Offset Scam",
        "Plastic Straws",
        "Eco Hypocrisy",
        "Heat Pump Hell",
        "Just Stop Oil",
        "Extinction Rebellion",
    ],
    "gypsies": [
        "Traveller Site",
        "Caravan",
        "Scrap Metal",
        "Fighting",
        "Wedding Chaos",
        "Police Raid",
        "Fortune Telling Scam",
        "Horses on Dual Carriageway",
        "Council Eviction",
        "Family Feud",
        "Stereotypes Meta",
        "Market Stall",
        "No Fixed Abode Flex",
    ],
    "hollywood": [
        "Awards Season",
        "Casting Couch",
        "Method Acting",
        "Box Office Flop",
        "Franchise Fatigue",
        "Actor Politics",
        "Plastic Surgery Town",
        "Studio Cover-ups",
        "Red Carpet",
        "Agent / Manager",
        "Writers Strike Energy",
        "Nepo Babies",
        "MeToo Hollywood",
    ],
    "homeless": [
        "Cardboard Box",
        "Begging Spiels",
        "Shelter Queue",
        "Bottle of Special Brew",
        "Dog on a String",
        "Under the Bridge",
        "Mental Illness Street",
        "Benefits Street Energy",
        "Soup Kitchen",
        "Sleeping Rough Winter",
        "Aggressive Begging",
        "Lost Everything Gambling",
        "Eviction",
        "Public Toilet Wash",
    ],
    "immigration": [
        "Small Boats",
        "Border Force",
        "Asylum Hotel",
        "Deportation",
        "Illegal Entry",
        "Work Visa Abuse",
        "Integration Fail",
        "Language Barrier",
        "Grooming Gang Adjacent",
        "Open Borders",
        "Citizenship Test",
        "Detention Centre",
        "Channel Crossing",
        "Removals Flight",
        "Culture Clash",
    ],
    "news": [
        "Breaking News",
        "Tabloid Scandal",
        "Weather Extreme",
        "Crime Wave Report",
        "Political Circus",
        "Celebrity Court Case",
        "Fake News Meta",
        "Local News Weird",
        "War Coverage",
        "Economy Doom",
        "Press Conference",
        "Leaked Documents",
        "Trial of the Century",
    ],
    "incest": [
        "Sibling Romance",
        "Parent-Child Dark",
        "Cousin Marriage",
        "Twincest",
        "Stepfamily",
        "Family Reunion Gone Wrong",
        "Genetic Punchline",
        "Secret Bloodline",
        "Royal Inbreeding",
        "Alabama Jokes",
        "Caught by Parents",
        "Forbidden Relative",
    ],
    "prison": [
        "Cellmate",
        "Prison Shower",
        "Contraband",
        "Guard Corruption",
        "Solitary",
        "Parole Denied",
        "Prison Tattoo",
        "Snitches",
        "Riot",
        "Death Row",
        "Prison Food",
        "Visiting Day",
        "Gang Inside",
        "Escaped Convict",
        "Life Sentence",
    ],
    "jeremyclarkson": [
        "Top Gear",
        "The Grand Tour",
        "Farm Arc",
        "Punch a Producer",
        "Clarkson's Mouth",
        "Fast Cars",
        "Hammond and May",
        "Argentina Special",
        "Newspaper Column",
        "Who Wants to Be a Millionaire",
        "Rural Rage",
        "Restaurant Reviews",
    ],
    "jews": [
        "Stereotypes Meta",
        "Holocaust Dark",
        "Israel / Gaza",
        "Money Jokes",
        "Bar Mitzvah",
        "Kosher",
        "Synagogue",
        "Antisemitism Meta",
        "Jewish Mother",
        "Nose Jokes",
        "Banker Tropes",
        "Diaspora",
        "Passover",
        "Jewish Christmas Avoidance",
    ],
    "gay": [
        "Coming Out",
        "Pride Parade",
        "Gay Marriage",
        "Closeted",
        "Grindr",
        "Lesbian Drama",
        "Bi Erasure Jokes",
        "Camp Culture",
        "Gay Panic",
        "Drag Queens",
        "Same-Sex Parenting",
        "AIDS Era Overlap",
        "Bear / Twink",
        "Rainbow Capitalism",
        "Conversion Therapy Dark",
    ],
    "story": [
        "Shaggy Dog Story",
        "Slow Burn Setup",
        "Twist Ending",
        "Unreliable Narrator",
        "True Story Allegedly",
        "Bar Story",
        "Travel Yarn",
        "War Story",
        "Family Saga",
        "Too Long Didn't Laugh",
        "Build-up Payoff",
    ],
    "marriage": [
        "Wedding Day Disaster",
        "Divorce",
        "Prenup",
        "Mother-in-Law",
        "Anniversary Forgotten",
        "Sexless Marriage",
        "Open Marriage",
        "Arranged Marriage",
        "Cold Feet",
        "Best Man Speech",
        "Honeymoon",
        "Alimony",
        "Cheating Spouse",
        "Shotgun Wedding",
        "Second Marriage",
    ],
    "masturbation": [
        "Caught in the Act",
        "Socks",
        "Lube Disaster",
        "Porn Browser History",
        "RSI / Carpal",
        "Religious Guilt",
        "Public Toilet Wank",
        "Fleshlight Fail",
        "Edging",
        "Post-Nut Clarity",
        "Sharing a Room",
        "Zoom Call Risk",
        "Teen Angst",
        "Semen Everywhere",
    ],
    "mentalhealth": [
        "Depression",
        "Anxiety",
        "Schizophrenia",
        "Bipolar",
        "Therapy Session",
        "Medication Side Effects",
        "Self-Harm Dark",
        "Psych Ward",
        "Hearing Voices",
        "OCD",
        "PTSD",
        "Personality Disorder",
        "Sectioned",
        "Wellness Culture Mock",
        "Hotline Joke",
    ],
    "motoring": [
        "Road Rage",
        "Speeding Ticket",
        "Drink Driving",
        "MOT Fail",
        "Boy Racer",
        "Parking Dispute",
        "Crash For Cash",
        "Hit and Run",
        "Number Plate",
        "Dieselgate Energy",
        "Learner Driver",
        "Motorway Pile-up",
        "Potholes",
        "Insurance Scam",
        "Classic Car Midlife",
    ],
    "murder": [
        "Serial Killer",
        "Crime of Passion",
        "Contract Kill",
        "Poisoning",
        "Stabbing",
        "Shooting",
        "Body Disposal",
        "Murder Mystery Party Real",
        "Domestic Murder",
        "Mass Shooting Dark",
        "Cold Case",
        "Accomplice",
        "Confession",
        "Death Penalty",
        "Murder-Suicide",
    ],
    "muslim": [
        "Mosque",
        "Ramadan",
        "Halal",
        "Burqa / Niqab",
        "Imam",
        "Extremism Punchline",
        "Honor Culture Dark",
        "Prophet Jokes Meta",
        "Hajj",
        "Friday Prayer",
        "Convert Stories",
        "Islamophobia Meta",
        "Sharia Gags",
        "Cousin Marriage Overlap",
    ],
    "nonjokes": [
        "Site Announcement",
        "Rule Reminder",
        "Mod Note",
        "Outage Notice",
        "Feature Request",
        "Thanks / Shoutout",
        "Not Actually Funny",
        "Meta Post",
        "Event Promo",
        "Apology",
    ],
    "rhymes": [
        "Twisted Nursery Rhyme",
        "Humpty Dumpty Dark",
        "Jack and Jill Dead",
        "Ring a Rosie Plague",
        "Three Blind Mice",
        "London Bridge",
        "Mary Had a Little...",
        "Baa Baa Black Sheep",
        "Lullaby Horror",
        "Playground Chant",
        "Alphabet Gore",
    ],
    "offensive": [
        "Maximum Edgelord",
        "Taboo Stacking",
        "Slur Dump",
        "Sacred Cow Slaughter",
        "Punch Down Masterclass",
        "Nobody is Safe",
        "Too Soon",
        "Too Far",
        "Banned Everywhere Else",
        "Trigger Warning Irony",
        "Hate Speech Cosplay",
        "Cancel Me Challenge",
    ],
    "paki": [
        "Corner Shop",
        "Taxi Driver",
        "Curry House",
        "Grooming Gang",
        "Cousin Marriage",
        "Arranged Marriage",
        "Bollywood Energy",
        "Partition Dark",
        "Mosque Overlap",
        "Import Bride",
        "Slur Reclaim Meta",
        "Birmingham / Bradford",
        "Cash Business",
    ],
    "pedo": [
        "Stranger Danger",
        "Teacher Scandal",
        "Youth Pastor",
        "To Catch a Predator Energy",
        "Computer Files",
        "Ice Cream Van",
        "Scout Leader",
        "Family Friend",
        "Online Grooming",
        "Prison Justice",
        "Map / Registry",
        "Celebrity Pedo",
        "Epstein Overlap",
        "Not a Joke Zone Meta",
    ],
    "political": [
        "Left Wing",
        "Right Wing",
        "General Election",
        "MP Scandal",
        "Brexit Forever",
        "Tax and Spend",
        "NHS Politics",
        "Local Council",
        "Lobbyists",
        "Spin Doctor",
        "Political Correctness",
        "Dictatorship Abroad",
        "Revolution Fantasy",
        "Coalition Chaos",
        "Prime Minister Roast",
    ],
    "porn": [
        "Hub Categories",
        "Amateur vs Pro",
        "VR Porn",
        "Step-Family Tropes",
        "Cumshot Logistics",
        "Pornstar Career",
        "Revenge Porn Dark",
        "Deepfake Porn",
        "Cam Sites",
        "Porn Addiction",
        "Incognito Mode Fail",
        "Unexpected Genre",
        "Censorship",
        "Porn Music",
        "Behind the Scenes Gross",
    ],
    "pranks": [
        "Workplace Prank",
        "Prank Gone Wrong",
        "YouTube Prankster",
        "Scare Prank",
        "Phone Prank",
        "Social Experiment",
        "April Fools",
        "Prank War Escalation",
        "Hidden Camera",
        "Public Embarrassment",
        "Prank on Partner",
        "Too Far Prank",
    ],
    "prostitute": [
        "Street Walker",
        "Escort Agency",
        "Brothel Raid",
        "Pimp",
        "Kerb Crawler",
        "OnlyFans Adjacent",
        "Hotel Callout",
        "STD Risk",
        "Undercover Cop",
        "Trafficking Dark",
        "Happy Ending Massage",
        "Sugar Baby",
        "Red Light District",
        "Price Negotiation",
    ],
    "racist": [
        "Classic Stereotypes",
        "Immigration Overlap",
        "Colourist Jokes",
        "Colonial Hangover",
        "Apartheid Dark",
        "KKK Energy",
        "Casual Workplace Racism",
        "Mixed Race",
        "Passport Bros",
        "National Rivalries",
        "Slur Encyclopedia",
        "Reverse Racism Meta",
        "Cricket Test Energy",
    ],
    "rape": [
        "Date Rape",
        "Stranger Attack",
        "Campus Assault",
        "Prison Rape",
        "Marital Rape",
        "False Accusation Meta",
        "War Rape Dark",
        "Survivors Group Dark",
        "Court Case",
        "Consent Grey Area Jokes",
        "MeToo Backlash",
        "Statutory",
        "Gang Rape Dark",
    ],
    "religion": [
        "Christianity",
        "Catholic Guilt",
        "Priest Scandal",
        "Atheism Flex",
        "Bible Literal",
        "Hell and Damnation",
        "Cults",
        "Creationism",
        "Prayer Fail",
        "Church Collection Plate",
        "End Times",
        "Blasphemy",
        "Interfaith Mess",
        "Televangelist",
        "Buddhist / Other",
    ],
    "reneegood": [
        "Renee Good Lore",
        "Public Meltdown",
        "Social Media Storm",
        "Cancel Attempt",
        "Comeback Tour",
        "Interview Disaster",
        "Fan Drama",
        "Brand Deal Fail",
        "Allegations",
        "Apology Video",
    ],
    "rosiejones": [
        "Comedy Circuit",
        "Disability Representation",
        "Panel Show",
        "Twitter Storm",
        "Punchline Backlash",
        "Live Tour",
        "Interview Clip",
        "Awards Night",
        "Controversy Cycle",
        "Stand-up Special",
    ],
    "scouser": [
        "Liverpool FC",
        "Everton",
        "Accent Mockery",
        "Scouse Wit",
        "Dockers",
        "Thieving Stereotype",
        "Beatles Overdose",
        "Council Estate",
        "Chippy Tea",
        "Derby Day",
        "Bootle / Toxteth",
        "Funny Bones",
    ],
    "selfdeprecating": [
        "Ugly Bastard",
        "Failure Resume",
        "Lonely",
        "Broke",
        "Bad at Sex",
        "Socially Useless",
        "Career Nowhere",
        "Addict Self-Roast",
        "Body Issues",
        "IQ Self-Own",
        "Friendless",
        "Therapy Needed",
        "I'm the Joke",
    ],
    "sex": [
        "Vanilla Sex",
        "Kinky Sex",
        "Bad in Bed",
        "Premature",
        "Dry Spell",
        "Public Sex",
        "Roleplay",
        "Sex Tape",
        "Morning Wood",
        "Period Sex",
        "Anal Adventures",
        "Group Sex",
        "Sex Education Fail",
        "Performance Anxiety",
        "Afterglow Arguments",
        "Weird Fetishes",
    ],
    "sexist": [
        "Kitchen Jokes",
        "Women Drivers",
        "Mansplaining Meta",
        "Glass Ceiling",
        "Objectification",
        "Equal Pay Banter",
        "Boys Club",
        "Feminism Roast",
        "Toxic Masculinity Flex",
        "Beauty Standards",
        "Domestic Roles",
        "Catcalling",
        "Male Tears",
    ],
    "siblings": [
        "Brother Rivalry",
        "Sister Drama",
        "Favourite Child",
        "Borrowed Clothes",
        "Shared Room Hell",
        "Sibling Betrayal",
        "Twins",
        "Half-Siblings",
        "Inheritance Fight",
        "Babysitting Abuse",
        "Tag Team Parents",
        "Estranged",
    ],
    "silly": [
        "Absurd",
        "Surreal",
        "Puns Adjacent",
        "Nonsense Words",
        "Cartoon Logic",
        "Animals Doing People Things",
        "Silly Walks Energy",
        "Toilet Humour Light",
        "Random What-If",
        "Daft Comparisons",
        "Childlike",
    ],
    "songs": [
        "Parody Lyrics",
        "Christmas Carol Twist",
        "Football Chant",
        "Nursery Song Dark",
        "Karaoke Disaster",
        "One-Hit Wonder",
        "National Anthem",
        "Hymn Corruption",
        "Rap Roast",
        "Musical Theatre",
        "Earworm",
    ],
    "sports": [
        "Olympics",
        "Boxing / MMA",
        "Tennis",
        "Golf Snobs",
        "Rugby",
        "Cricket",
        "Doping",
        "Injured Athlete",
        "Sports Gambling Overlap",
        "Coach Abuse",
        "Fan Violence",
        "Disabled Sports",
        "School PE Trauma",
        "Esports Nerds",
    ],
    "suicide": [
        "Bridge Jump",
        "Overdose",
        "Hanging",
        "Note Left Behind",
        "Failed Attempt",
        "Copycat Media",
        "Hotline Hold Music",
        "Survivor Guilt",
        "Assisted Dying",
        "Jumping in Front of Train",
        "Gunshot",
        "Pact",
        "After the Funeral",
        "Too Soon Meta",
    ],
    "tvmovies": [
        "Blockbuster Flop",
        "Streaming Filler",
        "Remake Worse",
        "Spoiler Alert",
        "Actor Who Can't Act",
        "Soap Opera",
        "True Crime Series",
        "Horror Trope",
        "Romcom Trash",
        "CGI Garbage",
        "Cancelled Mid-Season",
        "Product Placement",
        "Awards Bait",
    ],
    "trans": [
        "Pronouns",
        "Sports Debate",
        "Youth Transition",
        "Bathroom Wars",
        "Detransition",
        "Surgery Stories",
        "Autogynephilia Discourse",
        "Drag Overlap",
        "Women's Spaces",
        "Trans Day Of",
        "Social Contagion Claim",
        "Hormone Effects",
        "Deadname Energy",
        "Media Coverage",
    ],
    "vapeman": [
        "Vape Clouds",
        "Flavour Ban",
        "School Kids Vaping",
        "Exploding Device",
        "Nicotine Addict",
        "Vape Shop",
        "Disposable Vapes Litter",
        "Quit Smoking Fail",
        "Cloud Competitions",
        "Battery Swallow",
        "Secondhand Vapour",
    ],
    "vegan": [
        "Beyond Meat",
        "B12 Deficiency",
        "Preachy Vegan",
        "Cheese Withdrawal",
        "Factory Farming Roast",
        "CrossFit Vegan",
        "Impossible Burger",
        "Leather Shoes Hypocrisy",
        "Vegan Cats",
        "BBQ Invitation",
        "Protein Myths",
        "Lab Grown Meat",
    ],
    "wasp": [
        "Picnic Attack",
        "Nest in the Loft",
        "Sting Allergy",
        "Wasp vs Bee",
        "Flying Aggressive Bastards",
        "Cider Trap",
        "Exterminator",
        "One Wasp Ruins Summer",
        "Inside the Car",
        "Paper Nest",
    ],
    "weather": [
        "British Rain",
        "Heatwave Meltdown",
        "Snow Chaos",
        "Flooding",
        "Storm Names",
        "Tornado",
        "Climate Overlap",
        "Met Office Wrong Again",
        "Ice on the Roads",
        "Humidity Hell",
        "Drought Hose Ban",
    ],
    "wholesome": [
        "Actually Nice",
        "Acts of Kindness",
        "Animals Being Cute",
        "Grandparents Sweet",
        "Friendship Goals",
        "Feel-Good Twist",
        "Community Spirit",
        "Kids Being Kids",
        "Love Without Irony",
        "Hopeful Ending",
        "Wholesome Trap (Still Dark)",
    ],
    "wife": [
        "Nagging",
        "Shopping Habit",
        "Mother-in-Law Combo",
        "Bedroom Strike",
        "Wives vs Husbands",
        "Housework Scorekeeping",
        "Ball and Chain",
        "Anniversary Amnesia",
        "Wife's Best Friend",
        "Hidden Credit Card",
        "Cooking Complaints",
        "Ex-Wife",
        "Trophy Wife",
    ],
    "wordplay": [
        "Puns",
        "Double Entendre",
        "Homophones",
        "Anagrams",
        "Spoonerisms",
        "Knock-Knock",
        "Tom Swifty Energy",
        "Portmanteau",
        "Rhyme Time",
        "Misheard Lyrics",
        "Spelling Gags",
        "One-Liner Wordplay",
    ],
    "work": [
        "Lazy at Work",
        "Stealing from Work",
        "Late for Work",
        "Boss from Hell",
        "Meeting That Should Email",
        "HR Nightmare",
        "Office Affair",
        "Redundancy",
        "Work From Home Slacking",
        "Bullshitting Timesheets",
        "Health and Safety Theatre",
        "Union Dispute",
        "Minimum Wage",
        "Shift Work",
        "Customer is Always Wrong",
        "Printer Rage",
        "Team Building Hell",
        "Promotion by Brown-Nosing",
        "Quiet Quitting",
        "Resignation Fantasy",
    ],
}


def main() -> int:
    app = create_app()
    with app.app_context():
        cats = {c.slug: c for c in Category.query.all()}
        added = 0
        skipped = 0
        missing_slugs: list[str] = []

        for slug, names in SUBS.items():
            cat = cats.get(slug)
            if not cat:
                missing_slugs.append(slug)
                continue

            existing_rows = Subcategory.query.filter_by(category_id=cat.id).all()
            existing_slugs = {(s.slug or "").lower() for s in existing_rows}
            existing_names = {(s.name or "").strip().lower() for s in existing_rows}

            for name in names:
                name = name.strip()
                if not name:
                    continue
                if name.lower() in existing_names:
                    skipped += 1
                    continue

                sslug = slugify(name)
                base = sslug
                n = 2
                while sslug in existing_slugs:
                    sslug = f"{base}{n}"[:60]
                    n += 1
                    if n > 30:
                        break

                db.session.add(
                    Subcategory(
                        category_id=cat.id,
                        name=name,
                        slug=sslug,
                        sort_order=0,
                    )
                )
                existing_slugs.add(sslug)
                existing_names.add(name.lower())
                added += 1

        db.session.commit()
        total = Subcategory.query.count()
        print(f"added={added} skipped={skipped} total_subs_now={total}")
        if missing_slugs:
            print("missing category slugs:", ", ".join(missing_slugs))

        for slug in ("aids", "work", "dark", "sex", "cancer", "pedo", "rape"):
            c = cats.get(slug)
            if not c:
                continue
            n = Subcategory.query.filter_by(category_id=c.id).count()
            print(f"  {c.name}: {n} subcategories")

        empty = [
            c.name
            for c in Category.query.order_by(Category.name).all()
            if Subcategory.query.filter_by(category_id=c.id).count() == 0
        ]
        if empty:
            print("still empty:", ", ".join(empty))
        else:
            print("all categories have at least one subcategory")
    return 0


if __name__ == "__main__":
    sys.exit(main())
